### PR TITLE
master-qa-52723

### PR DESCRIPTION
**Pull request by zhangyan0701**
https://issues.liferay.com/browse/LRQA-52723

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by john-co** [comment]
ci:test:relevant

**Comment by john-co** [comment]
Looks good!

Pushed to BChan:
master: https://github.com/brianchandotcom/liferay-portal/pull/79834
7.2.x: https://github.com/brianchandotcom/liferay-portal-ee/pull/27175

**Pull request closed without merging**
