### PR TITLE
master-qa-61016

### PR DESCRIPTION
**Pull request by zhangyan0701**
https://issues.liferay.com/browse/LRQA-61016
https://issues.liferay.com/browse/LRQA-61017

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by john-co** [comment]
Just started reviewing :)

**Comment by john-co** [comment]
looks good!

**Review by john-co — APPROVED** [review]

**Comment by john-co** [comment]
ci:forward

**Pull request closed without merging**
