### PR TITLE
LPS-110927

### PR DESCRIPTION
**Pull request by kenjiheigel**

### CODE REVIEW

**Comment by kenjiheigel** [comment]
I fetched the branch on https://github.com/wincent/liferay-portal/pull/250 and removed Chema's commits for the test module and poshi changes. I converted his changes into Poshi. 

@john-co , see my example commit of how this works. The actually implementation of this will be up to you... 

I added `LiferayEvent.initializeLiferayEventLog` to `SignIn.signInTestSetup` because we run that macro for every test so that's a good place for a "hammer" approach. Otherwise, you'd have to put it in every *.testcase file. 

In terms of which SelectFrame usages you'll need to add this wait before, you'll need to find all of those... I don't think there's a clean place to apply this. I don't think we can say that every SelectFrame command we use in Poshi for portal will be used on a Liferay Modal, so there's not a "hammer" approach on that end. You'll probably need to see which tests fail out to know where to apply the `LiferayEvent.waitForLiferayEvent`

You can probably start with this approach temporarily, and we can make the javascript usage more granular (listening for the event only right before it's fired, instead of at the beginning of every test like how I have it set up) later on. What my changes on the Poshi side can help with are being able to contain that same code in a *.function file, rather than a macro file. Additionally, we could add something in Poshi that will execute some javascript code at the beginning of a test instead of us putting it in a random macro file, or in every *.testcase file.

**Comment by john-co** [comment]
ci:test:bundle

**Comment by markocikos** [comment]
See updated version https://github.com/john-co/liferay-portal/pull/291

**Comment by markocikos** [comment]
ci:close

**Pull request closed without merging**
