### PR TITLE
LRQA-57091 | master

### PR DESCRIPTION
**Pull request by john-co**
https://issues.liferay.com/browse/LRQA-57091

### CODE REVIEW

**Comment by john-co** [comment]
ci:forward

**Comment by michaelhashimoto** [comment]
Your pull request test has been aborted. We are sorry of the inconvenience but QA is in the process of refining the `ci:test:relevant` test suite. Unfortunately this particular pull request test has exceeded the maximum resource limit and will be aborted. Please contact your team's QA representative(s) for next steps. If your team does not have one then please make a post in [#d-quality-assurance](https://liferay.slack.com/archives/CL84ZPHAT)

**Comment by john-co** [comment]
ci:forward

**Comment by john-co** [comment]
ci:stop

**Comment by john-co** [comment]
ci:forward

**Pull request closed without merging**
