### PR TITLE
lps-95623

### PR DESCRIPTION
**Pull request by lawrence-lee**

### CODE REVIEW

**Comment by lawrence-lee** [comment]
ci:test:poshi

**Comment by lawrence-lee** [comment]
not sure why this failed... here's the console output

```
     [exec] com.liferay.poshi.runner.PoshiRunner > test[LocalFile.SampleProjectTemplates#WarHookTemplateSmoke] STANDARD_OUT
     [exec]     Checking to see if TCat is enabled...
     [exec] Test has logged in.
     [exec] Test has logged in.
     [exec] 
     [exec]     BUILD FAILED: "Test has logged in." is not present in console
     [exec]     /opt/dev/projects/github/liferay-portal/portal-web/test/functional/com/liferay/portalweb/tests/development/tools/projecttemplates/SampleProjectTemplates.testcase[WarHookTemplateSmoke]:100
     [exec] 
     [exec] 
     [exec] com.liferay.poshi.runner.PoshiRunner > test[LocalFile.SampleProjectTemplates#WarHookTemplateSmoke] STANDARD_ERROR
     [exec]     java.lang.Exception: "Test has logged in." is not present in console
     [exec]     	at com.liferay.poshi.runner.selenium.BaseWebDriverImpl.assertConsoleTextPresent(BaseWebDriverImpl.java:317)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]     	at java.lang.reflect.Method.invoke(Method.java:498)
     [exec]     	at com.liferay.poshi.runner.PoshiRunnerExecutor$1.call(PoshiRunnerExecutor.java:1179)
     [exec]     	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
     [exec]     	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
     [exec]     	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
     [exec]     	at java.lang.Thread.run(Thread.java:745)
     [exec] 
```

**Comment by lawrence-lee** [comment]
hey @john-co, Can you please take a look at https://github.com/john-co/liferay-portal/pull/129#issuecomment-493725723. I would like to have these tests merged.

**Comment by john-co** [comment]
Pull request submitted to https://github.com/john-co/liferay-portal/pull/145. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by john-co** [comment]
Pull request submitted to https://github.com/lawrence-lee/liferay-portal/pull/123. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
