### PR TITLE
LRQA-61016, LRQA-61017 | master

### PR DESCRIPTION
**Pull request by zhangyan0701**
https://issues.liferay.com/browse/LRQA-61016
https://issues.liferay.com/browse/LRQA-61017

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by john-co** [comment]
https://stackoverflow.com/questions/42955330/sikuli-java-selenium-how-to-detect-image-background-colour-change
May need to include some other parts of the page in the sikuli image to make the color change more detectable. It may introduce some unwanted change detection though...so need to find something that will likely not change over time.

If not possible then, another option is to assert the css color hex value on the page.

**Pull request closed without merging**
