### PR TITLE
master-qa-55921

### PR DESCRIPTION
**Pull request by zhangyan0701**
https://issues.liferay.com/browse/LRQA-55921

This is for master only.

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by john-co** [comment]
ci:test

**Comment by john-co** [comment]
Pull request forwarded to https://github.com/brianchandotcom/liferay-portal/pull/85171. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
