### PR TITLE
pull-request-123

### PR DESCRIPTION
**Pull request by lawrence-lee**

### CODE REVIEW

**Comment by lawrence-lee** [comment]
ci:test

**Comment by lawrence-lee** [comment]
hey @john-co, I think this is ready for review. Thanks

**Comment by john-co** [comment]
Just started reviewing :)

**Comment by john-co** [comment]
Hi @lawrence-lee, looks good to me! The failures are not unique to this pull.

**Comment by lawrence-lee** [comment]
Hey @john-co, 
Is there anything else I would need to do to get this to upstream? Or has it been moved further along already?

**Comment by john-co** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/75727. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by john-co** [comment]
Pull request submitted to https://github.com/john-co/liferay-portal/pull/148. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
