### PR TITLE
LRQA-55018

### PR DESCRIPTION
**Pull request by kenjiheigel**
@john-co, can you try this? I couldn't get your use case to work, but it worked in a simple usecase that I made

### CODE REVIEW

**Comment by kenjiheigel** [comment]
I made this simple testcase and it worked: 
```
@component-name = "portal-smoke"
definition {

	property testray.main.component.name = "Smoke";

	setUp {
		Open(locator1 = "http://github.com");
	}

	test CopyPaste {
		DoubleClick(locator1 = "//h1");

		RobotType.robotTypeShortcut(locator1 = "Command + c");

		Click(locator1 = "//input");

		RobotType.robotTypeShortcut(locator1 = "Command + v");

		Pause(locator1 = "10000");
	}

}
```

I can't test the Ctrl key cause it's different, but I guess it would be: 
```
@component-name = "portal-smoke"
definition {

	property testray.main.component.name = "Smoke";

	setUp {
		Open(locator1 = "http://github.com");
	}

	test CopyPaste {
		DoubleClick(locator1 = "//h1");

		RobotType.robotTypeShortcut(locator1 = "Ctrl + c");

		Click(locator1 = "//input");

		RobotType.robotTypeShortcut(locator1 = "Ctrl + v");

		Pause(locator1 = "10000");
	}

}
```

**Comment by kenjiheigel** [comment]
If this works, just a reminder I'll have to send up the Poshi Runner changes first and do a poshi release before you guys can add the new test.

**Comment by john-co** [comment]
Thanks @kenjiheigel!

@zhangyan0701, can you please verify that this works on our usecase and CI?

**Comment by zhangyan0701** [comment]
Thanks @kenjiheigel  @john-co for working on this. 
I tried on local and the robotType worked on the usecase by using Ctrl key. I run ci test [here](https://github.com/zhangyan0701/liferay-portal/pull/152) to see if it work on CI as well.

Thanks again!

**Comment by zhangyan0701** [comment]
Hi @john-co @kenjiheigel ,
The new method also works on CI. See the result [here](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=1066142833).

@kenjiheigel Please add the methods into Poshi Runner when you have time, Thanks in advance!

**Comment by john-co** [comment]
Awesome, thanks @zhangyan0701!

**Pull request closed without merging**
