### PR TITLE
LPS-91967 Yarn

### PR DESCRIPTION
**Pull request by petershin**
@jbalsas

### CODE REVIEW

**Comment by petershin** [comment]
ci:test

**Comment by petershin** [comment]
@jbalsas - just fyi, I saw the error below. I worked around it by running `git clean -fdx`.

Is there an argument or flag that can be set to prevent this from happening for other devs?

```
yarn install v1.13.0

<--- Last few GCs --->

[9596:0000026FF44486E0]    37720 ms: Scavenge 1380.7 (1422.7) -> 1380.1 (1423.2) MB, 4.8 / 0.0 ms  (average mu = 0.143, current mu = 0.083) allocation failure
[9596:0000026FF44486E0]    37727 ms: Scavenge 1380.9 (1423.2) -> 1380.3 (1423.7) MB, 4.2 / 0.0 ms  (average mu = 0.143, current mu = 0.083) allocation failure
[9596:0000026FF44486E0]    37733 ms: Scavenge 1381.1 (1423.7) -> 1380.5 (1424.7) MB, 3.6 / 0.0 ms  (average mu = 0.143, current mu = 0.083) allocation failure


<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0000006233B5C5C1]
    1: StubFrame [pc: 0000006233B10821]
    2: StubFrame [pc: 0000006233B4500C]
    3: StubFrame [pc: 0000006233B4BEA2]
Security context: 0x0249de21e6e1 <JSObject>
    4: replace [00000249DE2105E1](this=0x0375cb1aca41 <String[97]: P:\project\lfm\portal\modules\apps\layout\layout-content-page-editor-web\node_modules\got\license>,0x0375cb1aca69 <JSRegExp <String[2]: \\>>,0x033ef23af831 <String[1]: />)...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 00007FF735290EFA v8::internal::GCIdleTimeHandler::GCIdleTimeHandler+4810
 2: 00007FF73526A296 node::MakeCallback+4518
 3: 00007FF73526AC80 node_module_register+2160
 4: 00007FF7355009BE v8::internal::FatalProcessOutOfMemory+846
 5: 00007FF7355008EF v8::internal::FatalProcessOutOfMemory+639
 6: 00007FF735A3E954 v8::internal::Heap::MaxHeapGrowingFactor+11476
 7: 00007FF735A350B7 v8::internal::ScavengeJob::operator=+25543
 8: 00007FF735A3362C v8::internal::ScavengeJob::operator=+18748
 9: 00007FF735A3C5A7 v8::internal::Heap::MaxHeapGrowingFactor+2343
10: 00007FF735A3C626 v8::internal::Heap::MaxHeapGrowingFactor+2470
11: 00007FF7355DF0CB v8::internal::Factory::AllocateRawWithImmortalMap+59
12: 00007FF7355E1BCD v8::internal::Factory::NewRawTwoByteString+77
13: 00007FF7357F5C58 v8::internal::Smi::SmiPrint+536
14: 00007FF7354F3ECB v8::internal::StringHasher::UpdateIndex+219
15: 00007FF73580F9D5 v8::internal::SlicedString::SlicedStringGet+4805
16: 00007FF7358D20C4 v8::internal::RegisterConfiguration::AreAliases+73812
17: 0000006233B5C5C1
```

**Comment by john-co** [comment]
ci:test

**Comment by john-co** [comment]
@petershin looks like there's a compile failure related to yarn.

**Comment by jbalsas** [comment]
I’ll take it from here tomorrow :(

**Comment by john-co** [comment]
Closing pull, resend when ready after fix.

**Comment by jbalsas** [comment]
This works locally, so it's likely a CI issue now 😭

**Comment by jbalsas** [comment]
ci:reopen

**Comment by jbalsas** [comment]
@john-co, @petershin, could we run this on a higher debug level to understand what's going on? I suspect the node_modules caching mechanism. Could we disable it somehow to see if the CI build completes?

**Comment by john-co** [comment]
@jbalsas I was able to reproduce the issue locally yesterday when I fetched this pull.

**Comment by jbalsas** [comment]
Did you ran `git clean -fdx` prior to `ant all`?

**Comment by john-co** [comment]
> Did you ran `git clean -fdx` prior to `ant all`?

ah, I did not. Let me check that.

**Comment by john-co** [comment]
@jbalsas I'll look into this further with CI team.

**Comment by jbalsas** [comment]
Let's start by disabling the npm caching mechanism, just to make sure this works!

**Comment by john-co** [comment]
Closing as peter will send updated pull

**Pull request closed without merging**
