### PR TITLE
LPS-XXXXX Uses @clayui/css (v3) instead of clay-css (v2) of Clay

### PR DESCRIPTION
**Pull request by jbalsas**
Hey @john-co, this is a preliminary test. Could you please run a full suite of tests and also do a more or less thorough manual test to see how things look like?

We should be moving here from clay-css v2 to @clayui/css v3, so we won't be needing to backport changes to 2.x anymore.

/cc @pat270, @marcoscv-work, @eduardoallegrini

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test

**Comment by john-co** [comment]
ci:test:bundle

**Comment by john-co** [comment]
ci:test:relevant

**Comment by john-co** [comment]
ci:test

**Comment by john-co** [comment]
ci:test:sf

**Comment by john-co** [comment]
Differences observed based on [comparison screenshots](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=945200990&testrayRunIdA=952809202&statusB=3):
- Logo text font size is bigger. [AppBuilder#PublishAppAsWidgetAndSubmitEntry](https://testray.liferay.com/home/-/testray/case_results/952841073)
-- v2 clay
v2_LogoFont
-- v3 clay
v3_LogoFontLarger

- `Adding Widgets` text font size is bigger. [Microblogs#EditEntry
Result](https://testray.liferay.com/home/-/testray/case_results/952818421)
-- v2 clay
v2_AddWidgetFont
-- v3 clay 
v3_AddWidget font

**Comment by john-co** [comment]
**Reviewed. Test failures are unrelated**. :heavy_check_mark: 

**Comparison Details:**
https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=950839622&testrayRunIdA=952809202&statusB=2

- Observed visual font size differences` in logo and `adding widgets`

**Comment by marcoscv-work** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcoscv-work** [comment]
https://github.com/liferay/clay/issues/2864

**Pull request closed without merging**
