### PR TITLE
master-qa-60155

### PR DESCRIPTION
**Pull request by zhangyan0701**
https://issues.liferay.com/browse/LRQA-60155

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
Hi @john-co 

I added an ant target in build-test.xml file to deploy theme.war via deploy folder, if we update the ArchiveUtil, we may need to wait for the next poshi-runner release. Can you take a look? Do you think this is ok?

**Comment by john-co** [comment]
Hi @zhangyan0701 looks great! good job!

**Comment by john-co** [comment]
ci:forward

**Pull request closed without merging**
