### PR TITLE
master-qa-55018

### PR DESCRIPTION
**Pull request by zhangyan0701**
https://issues.liferay.com/browse/LRQA-55018

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by john-co** [comment]
test

**Comment by john-co** [comment]
Pushed to KHeigel

liferay-portal/pull/553

**Comment by john-co** [comment]
test google [link](http//www.google.com)

**Comment by john-co** [comment]
test github [link](https://github.com/kenjiheigel)

**Comment by john-co** [comment]
Pushed to KHeigel.
master: https://github.com/kenjiheigel/liferay-portal/pull/553

For some reason github wouldn't let me comment the above a few minutes ago...

**Pull request closed without merging**
