### PR TITLE
LRQA-66397 Add Clay Sample Portlet property to Clay tests

### PR DESCRIPTION
**Pull request by nkkwon**
https://issues.liferay.com/browse/LRQA-66397
Testing

### CODE REVIEW

**Comment by nkkwon** [comment]
ci:test:license

**Comment by john-co** [comment]
ci:test:frontend

**Comment by john-co** [comment]
we can look at the logs and search for `deploy-osgi-modules:` if we see the clay sample module being built and deployed then that should validate that the property works for the test on CI

I tested the property locally and it works with these commits https://github.com/john-co/liferay-portal/pull/410 
command: `ant -f build-test-tomcat.xml run-selenium-tomcat -Dtest.class="ClaySelect#SmokeMultipleSelect"`

**Comment by john-co** [comment]
Clay tests [failed on compiling the osgi module](https://testray.liferay.com/home/-/testray/case_results/1534264227?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D1534264173%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)...will need to investigate more on how to resolve.

**Comment by john-co** [comment]
ci:test:frontend

**Comment by john-co** [comment]
It looks like the generated `node_modules` directory is picked up by the osgi pattern. Retesting with the exclusion.

```
deploy-osgi-modules:
     [move] Warning: Could not find file /opt/dev/projects/github/liferay-portal/modules/node_modules/settings.gradle to copy.
```

**Comment by john-co** [comment]
Looks like the fix worked, pushing to https://github.com/liferay-frontend/liferay-portal/pull/1093

**Pull request closed without merging**
