### PR TITLE
LPS 122074 | Removing IE11 macros and paths from master

### PR DESCRIPTION
**Pull request by calvinctvo**
https://issues.liferay.com/browse/LPS-122073
https://issues.liferay.com/browse/LPS-122074
1. Removing macros with `"${browserType}" == "internetexplorer"` from master branch
2. Removing paths with `"IE_11"` from master branch

### CODE REVIEW

**Comment by calvinctvo** [comment]
ci:test:sf

**Comment by calvinctvo** [comment]
ci:test:relevant

**Review by john-co — CHANGES_REQUESTED** [review]
Like I mentioned before, `"${browserType}" == "internetexplorer"` is a good search and there's some results in `.testcase` and `.macro` files. You'll also want to remove the `var browserType = PropsUtil.get("browser.type");` if they're only targeting internetexplorer.

image

**Comment by john-co** [comment]
I plan to forward this to liferay-frontend user. Please add a description of the task and test plan to the initial commit so other reviewers may know the context.

**Comment by calvinctvo** [comment]
ci:test:sf

**Comment by calvinctvo** [comment]
ci:test:relevant

**Comment by john-co** [comment]
Pull request forwarded to https://github.com/liferay-frontend/liferay-portal/pull/508. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
