### PR TITLE
master-qa-52467

### PR DESCRIPTION
**Pull request by zhangyan0701**
https://issues.liferay.com/browse/LRQA-52467

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by john-co** [comment]
looks good to me, thanks @zhangyan0701!

**Comment by john-co** [comment]
Pushed to 
master: https://github.com/brianchandotcom/liferay-portal/pull/79362
7.2.x: https://github.com/brianchandotcom/liferay-portal-ee/pull/26911

**Pull request closed without merging**
