### PR TITLE
LPS-94798

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @john-co,

Attached is an update for http://issues.liferay.com/browse/LPS-94798.

I am sending this to you for review of the tests since last time it cause a bunch of regressions.   See https://github.com/brianchandotcom/liferay-portal/pull/73486.

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by john-co** [comment]
ci:test:bundle

**Comment by john-co** [comment]
ci:test:relevant

**Comment by john-co** [comment]
Hi @jonmak08, I didn't observe any regressions caused by this pull. However, it does provide the expected behavior. The pagination moves to the bottom right but the ticket is expecting the pagination list to appear on top.
Selection_002

**Comment by jonmak08** [comment]
New Pull Request: https://github.com/fortunatomaldonado/liferay-portal/pull/5

**Pull request closed without merging**
