### PR TITLE
LPS-105791 Stop excluding symbol-observable

### PR DESCRIPTION
**Pull request by izaera**

### CODE REVIEW

**Comment by izaera** [comment]
ci:test

**Comment by izaera** [comment]
@john-co :thinking: this :point_up: failed for me spuriously in local, but was fixed by running `yarn` manually in the `modules` folder. I wonder if the mirror is wrong...

**Comment by john-co** [comment]
ci:test:sf

**Comment by john-co** [comment]
ci:test:relevant

**Comment by john-co** [comment]
ci:test:sf

**Comment by john-co** [comment]
Hi @izaera, looks like the pull is failing on a different yarn issue. Possibly the credentials for liferay-npm-bundler-loader-css-loader in the yarn.lock file needs to be corrected?

I'm able to reproduce this locally:
```     [exec] > Task :yarnInstallModules
     [exec] yarn install v1.13.0
     [exec] [1/4] Resolving packages...
     [exec] [2/4] Fetching packages...
     [exec] error https://registry.yarnpkg.com/liferay-npm-bundler-loader-css-loader/-/liferay-npm-bundler-loader-css-loader-2.16.2.tgz: Integrity check failed for "liferay-npm-bundler-loader-css-loader" (computed integrity doesn't match our records, got "sha1-ZsuGYQVIEUcPfswLOJmA9nj1kUY= sha512-nApromE24RvytmNzpOivvUvSxgTgYxI7deWTbQUQH5i4ZJONTtZ09T4cCIfhEmVz91OxZMmREnyF/nP2IXCxgQ==")
     [exec] info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by john-co** [comment]
Updated yarn.lock file and pushed to https://github.com/john-co/liferay-portal/pull/224 for further review

**Pull request closed without merging**
