### PR TITLE
master-qa-52709

### PR DESCRIPTION
**Pull request by zhangyan0701**
https://issues.liferay.com/browse/LRQA-52709

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by john-co** [comment]
Hi @zhangyan0701,

This may be a temporary workaround to skip something that may seem trivial but I don't want to turn a blind eye on it. 

This issue doesn't seem exclusive to IE11. https://issues.liferay.com/browse/LRQA-52951

I created LRCI-704 to get some help with verifyClick method available for us. I think this will be a better workaround. Let's look more into this.

**Comment by john-co** [comment]
Pushed to BChan:
master: https://github.com/brianchandotcom/liferay-portal/pull/80483
7.2.x: https://github.com/brianchandotcom/liferay-portal-ee/pull/27444

**Comment by john-co** [comment]
Pushing in the workaround since it will take a while for LRCI-704 to be implemented. Would rather complete the testcase to discover a real regression than be stuck on this.

**Pull request closed without merging**
