### PR TITLE
master-qa-56477

### PR DESCRIPTION
**Pull request by zhangyan0701**
https://issues.liferay.com/browse/LRQA-56477

This is for master only. Thanks!

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by john-co** [comment]
Just started reviewing :)

**Comment by john-co** [comment]
Pull request forwarded to https://github.com/brianchandotcom/liferay-portal/pull/86181. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
