### PR TITLE
master-qa-52718

### PR DESCRIPTION
**Pull request by zhangyan0701**
https://issues.liferay.com/browse/LRQA-52718

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by john-co** [comment]
Just started reviewing :)

**Comment by john-co** [comment]
lgtm! :heavy_check_mark:

**Comment by john-co** [comment]
pushed to BChan:
master: https://github.com/brianchandotcom/liferay-portal/pull/84640
7.2.x: https://github.com/brianchandotcom/liferay-portal-ee/pull/29001

**Pull request closed without merging**
