### PR TITLE
LPS-129309 | master

### PR DESCRIPTION
**Pull request by john-co**
https://issues.liferay.com/browse/LPS-129309

### CODE REVIEW

**Comment by john-co** [comment]
ci:test:relevant

**Comment by john-co** [comment]
ci:test:help

**Comment by john-co** [comment]
ci:help

**Comment by john-co** [comment]
ci:stop:help

**Comment by john-co** [comment]
ci:test:poshi

**Comment by john-co** [comment]
ci:test:relevant

**Comment by john-co** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
Just started reviewing :)

**Comment by zhangyan0701** [comment]
Hi @john-co 

I divided the failures into four groups:

1.
[LocalFile.AppBuilderWorkflow#CreateFormViewThroughWorkflowAppBuilder](https://testray.liferay.com/home/-/testray/case_results/1525626036)
custom object

This one is really weird, the tooltip of my custom object pops up before opening the modal frame, but it didn't disappear after opening the modal, and covers the text field. I wasn't able to reproduce this manually.

2.
[LocalFile.ContentPageConverter#EditConvertedContentPageWithDecorator](https://testray.liferay.com/home/-/testray/case_results/1525626133)
[LocalFile.WebContentSearch#SearchWebContentTag](https://testray.liferay.com/home/-/testray/case_results/1525626693)
[LocalFile.UIInfrastructureUsecase#Smoke](https://testray.liferay.com/home/-/testray/case_results/1525626566)

Seems like in these cases, the mouseover is necessary before click the elements (Portlet title, search input field and close modal icon).

3.
[LocalFile.LocalizedSimpleFieldsetsStructure#TranslateStructureWithFieldsetAndNested](https://testray.liferay.com/home/-/testray/case_results/1525626582)
[LocalFile.SharedAppBuilder#CreateRemoveUpdateDeleteEntriesOfProductMenuApp](https://testray.liferay.com/home/-/testray/case_results/1525626664)
[LocalFile.AppBuilder#ViewFormViewRules](https://testray.liferay.com/home/-/testray/case_results/1525626027)
[LocalFile.AppBuilder#PropagateChangesInFieldset](https://testray.liferay.com/home/-/testray/case_results/1525625989)
[LocalFile.DMSmoke#DeleteDocumentWithFieldsFromCustomDocTypeAndMetadataSet](https://testray.liferay.com/home/-/testray/case_results/1525626311)

These cases all failed when double click DDM field. It supposed to click the field, but click on the tooltip instead.

4.
[LocalFile.CollectionDisplay#ViewManualCollectionWithAssetTypes](https://testray.liferay.com/home/-/testray/case_results/1525626111)
[LocalFile.CollectionCategoryFilter#FilterResultsOfCollectionPageBasedOnManualCollectionBySingleCategory](https://testray.liferay.com/home/-/testray/case_results/1525626107)
[LocalFile.CollectionCategoryFilter#FilterResultsOfCollectionPageBasedOnManualCollectionByContainsAnyCategories](https://testray.liferay.com/home/-/testray/case_results/1525626105)
[LocalFile.PagesAdmin#GoToCollectionItemDisplayPage](https://testray.liferay.com/home/-/testray/case_results/1525626632)
[LocalFile.CollectionDisplay#ViewTitleOfCollectionItems](https://testray.liferay.com/home/-/testray/case_results/1525626122)

These tests failed because the mouseover in Check.function, the paths in these tests with `@title` that turns into `@data-restore-title` when mouseover.

I tried to remove selenium.mouseOver in Check.clickAt and running one test locally, but didn't fix it. In my test, the row entry could be checked, but failed with the same error when assert it is checked. See this screenshot on my local:
after0

I think because the Select tooltip pops up, so the path couldn't be found. But I don't understand why the tooltip appears since I already remove the mouseover.

And should the Select Blogs Entry tooltip displays at the bottom of the modal?

**Pull request closed without merging**
