### PR TITLE
test-sf | master

### PR DESCRIPTION
**Pull request by john-co**
https://issues.liferay.com/browse/test-sf

### CODE REVIEW

**Comment by john-co** [comment]
ci:test:sf:norebase

**Comment by john-co** [comment]
ci:test:sf:norebase

**Comment by petershin** [comment]
@john-co - I copied this branch and reran the same CI test.  https://github.com/petershin/liferay-portal/pull/635

The CI output doesn't match yours though.  Is there a step that I'm missing?

**Comment by john-co** [comment]
ci:test:sf

**Comment by john-co** [comment]
ci:test:sf

**Pull request merged**
