### PR TITLE
master-qa-59373-1

### PR DESCRIPTION
**Pull request by zhangyan0701**
https://issues.liferay.com/browse/LRQA-59373

Tested in https://github.com/zhangyan0701/liferay-portal/pull/203#issuecomment-654227551, I think the failures are unrelated.

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
ci:test

**Comment by john-co** [comment]
Just started reviewing :)

**Comment by john-co** [comment]
so close...there's some other PortalSmoke#Smoke tests that are failing now from ci:test. :(
Seems flaky since they didn't appear in ci:test:relevant. Could you investigate further?

test-portal-acceptance-pullrequest-batch(master)/lpkg-base-jdk8
test-portal-acceptance-pullrequest-batch(master)/archived-module-smoke-jdk8

**Comment by john-co** [comment]
rerunning failed test batches in https://github.com/john-co/liferay-portal/pull/312, including other PortalSmoke tests as a control.

**Comment by zhangyan0701** [comment]
lpkg-base-jdk8 is passing in PR https://github.com/john-co/liferay-portal/pull/312.

archived-module-smoke-jdk8 is failed. I think it failed because it ran initialize Liferay Event javascript before the click operation fully completed. After clicking Add button, the iframe should be closed, but it didn't close immediately. I am thinking how to make sure it run the script after the click operation fully completed.

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
ci:test

**Comment by zhangyan0701** [comment]
I was trying with adding a waitforelementpersent function to wait for //body before running javascript. But still don't work.

Also tested in https://github.com/zhangyan0701/liferay-portal/pull/213#issuecomment-656019429. 

lpkg-base-jdk8 passed in that PR, but failed in this one.
archived-modules-test-jdk8 failed in both PRs when adding the second page, but the first page could be added successfully.

I am not sure how these failures related to the changes that I made.

@john-co Could you help me a little bit with these failures when you get a chance? Thanks in advance!

**Comment by john-co** [comment]
I looked into it but I can't tell what's interrupting the `archived-modules-test-jdk8`. I think we can remove the `//body` check since it brought back the lpkg-base-jdk8 regression.

I created https://issues.liferay.com/browse/LRCI-1490 to see if we can do a soft check since it's not necessarily important to fail the test if it can't detect a liferay event was fired.

**Comment by zhangyan0701** [comment]
Rebase and test in PR https://github.com/zhangyan0701/liferay-portal/pull/223 to see how it goes this time.

**Pull request closed without merging**
