### PR TITLE
LPS-110927 Update Liferay.Portlet.openWindow utility

### PR DESCRIPTION
**Pull request by markocikos**
Hey @john-co ,

Task history:
- https://github.com/wincent/liferay-portal/pull/219
- https://github.com/wincent/liferay-portal/pull/230
  - spinoff https://github.com/markocikos/liferay-portal/pull/187
- https://github.com/wincent/liferay-portal/pull/234
- https://github.com/wincent/liferay-portal/pull/239

Changes to https://github.com/wincent/liferay-portal/pull/239:
- Added firing of custom event when modal iframe is loaded, `modalIframeLoaded`, so CI tests can hook onto this event. Both new `openModal` and old AUI-based `LiferayModal` throw this event.
- I removed [this commit](https://github.com/wincent/liferay-portal/pull/239/commits/c2e51a009317f705dbe138e339aea384b03d14c6) . If I understood correctly, this will not be needed if we are using new custom event. If I got it wrong, please cherry-pick it back.

Please update CI tests to use the new custom event.

Thank you!

/cc @jbalsas @wincent

### CODE REVIEW

**Comment by john-co** [comment]
ci:test:bundle

**Comment by john-co** [comment]
As discussed in channels, it doesn't look like we currently have an easy way to use a listener which `Liferay.on` looks like. It would be more feasible if we had an attribute or an object that we could get somewhere. And we can incorporate it with something like in https://github.com/liferay/liferay-portal/blob/master/portal-web/test/functional/com/liferay/portalweb/macros/MetalComponent.macro#L21-L44

Testing alternative locators on the meantime in https://github.com/john-co/liferay-portal/pull/284

**Comment by jbalsas** [comment]
Just for reference. If we instrument tests with this little JS snippet: 

```javascript
const TRACKED_EVENTS = [
	'addPortlet',
	'allPortletsReady',
	'allUploadsComplete',
	'beforeNavigate',
	'beforeScreenFlip',
	'closePortlet',
	'dataLayoutConfigReady',
	'destroyPortlet',
	'editorAPIReady',
	'endNavigate',
	'form:registered',
	'formNavigator:reveal',
	'dropdownShow',
	'entitySelectionRemoved',
	'exitNavigation',
	'hideNavigationMenu',
	'initLayout',
	'inputLocalized:localeChanged',
	'noticeShow',
	'noticeHide',
	'popupReady',
	'portletDragStart',
	'portletMoved',
	'portletReady',
	'ratings:vote',
	'screenActivate',
	'screenDeactivate',
	'screenFlip',
	'screenLoad',
	'search-container:registered',
	'sessionExpired',
	'showNavigationMenu',
	'spaRequestTimeout',
	'startNavigate',
	'submitForm',
	'tempFileRemoved',
	'toggleControls',
	'updatedLayout',
];

window.LFR_JS_EVENTS_LOG = {};

Liferay.on(TRACKED_EVENTS, event => {
	const eventLog = LFR_JS_EVENTS_LOG[event.type] ? [...LFR_JS_EVENTS_LOG[event.type], event] : [event];

	LFR_JS_EVENTS_LOG = {
		...LFR_JS_EVENTS_LOG,
		[event.type]: eventLog
	};
});
```

Then we can wait for conditions doing something like:

```java
public boolean waitForSomething(String type, String foo) {
    wait.until((ExpectedCondition<Boolean>) wd ->
   ((JavascriptExecutor) wd).executeScript("LFR_JS_EVENTS_LOG['" + event.type + "'][LFR_JS_EVENTS_LOG.length-1]).equals...
	}
```

/cc @manoelcyreno, can you help us out throughout the day with this?

**Comment by john-co** [comment]
cc/ @kenjiheigel, fyi for the js snippet above, I'll be on later this afternoon to revisit.

**Comment by wincent** [comment]
Superseded by: https://github.com/wincent/liferay-portal/pull/250

**Comment by wincent** [comment]
ci:close

**Pull request closed without merging**
