### PR TITLE
LPS-107374 | master

### PR DESCRIPTION
**Pull request by john-co**
https://issues.liferay.com/browse/LPS-107374

### CODE REVIEW

**Comment by john-co** [comment]
ci:test:sf

**Comment by john-co** [comment]
ci:test:relevant

**Comment by john-co** [comment]
ci:stop

**Comment by julien** [comment]
@john-co thanks, re-sent here https://github.com/brianchandotcom/liferay-portal/pull/85713

**Comment by john-co** [comment]
ci:test:sf

**Comment by john-co** [comment]
ci:test:relevant

**Comment by john-co** [comment]
ci:stop

**Pull request closed without merging**
