### PR TITLE
LRQA-44612 - Update liferay-jest-junit-reporter dependency

### PR DESCRIPTION
**Pull request by bryceosterhaus**

### CODE REVIEW

**Comment by john-co** [comment]
ci:test

**Comment by john-co** [comment]
Pull request submitted to https://github.com/john-co/liferay-portal/pull/54. [See changes here.](https://github.com/john-co/liferay-portal/compare/c953c18fc1fac~1...c953c18fc1fac) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by john-co** [comment]
ci:reopen

**Comment by john-co** [comment]
> @bryceosterhaus as discussed, needs package-lock.json to be updated and missing some jest output https://gist.github.com/john-co/98bcce5d3eb3e4674bf781159fc5665b#file-gistfile1-txt-L10-L16.

@jbalsas, the TEST-frontend-js.xml files look good for initial and this pull is ready for your review. Please update package-lock.json. We can submit changes to jest output later.

**Comment by bryceosterhaus** [comment]
updated with regenerated package-lock files

**Comment by john-co** [comment]
ci:test

**Comment by bryceosterhaus** [comment]
ci:test

**Comment by bryceosterhaus** [comment]
ci:test

**Comment by bryceosterhaus** [comment]
sent new PR https://github.com/john-co/liferay-portal/pull/55

**Pull request closed without merging**
