### PR TITLE
master-qa-52722

### PR DESCRIPTION
**Pull request by zhangyan0701**
https://issues.liferay.com/browse/LRQA-52722
https://issues.liferay.com/browse/LRQA-52717

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by john-co** [comment]
Just started reviewing :)

**Comment by john-co** [comment]
looks good! 
pushed to:
master: https://github.com/brianchandotcom/liferay-portal/pull/79722
7.2.x: https://github.com/brianchandotcom/liferay-portal-ee/pull/27122

**Pull request closed without merging**
