### PR TITLE
LPS-110556 - Remove id scope since this style is needed for all dropdowns

### PR DESCRIPTION
**Pull request by bryceosterhaus**
Hey @john-co, could you do a sanity check for me on this change and verify dropdowns working correctly when the locale it rtl("ar" for example). This relates to this issue, https://github.com/liferay/clay/issues/2971

No need to follow those steps exactly, just need a sanity check that dropdowns look fine in both rtl and ltr.

Thanks!

### CODE REVIEW

**Comment by john-co** [comment]
ci:test:bundle

**Comment by john-co** [comment]
ci:test:relevant

**Comment by john-co** [comment]
Sorry didn't notice this until recently, my email notifications have been acting weird as of late. I'll take a closer look when tests are finished. Most likely tomorrow morning.

**Comment by john-co** [comment]
ci:test:forms

**Comment by john-co** [comment]
Hi @bryceosterhaus, I don't see a difference between the rtl and ltr for datepicker.

EN local

ENlocale_datePicker

AR local

ARlocale_datePicker

Just to clarify, are we expecting the AR locale to have the datepicker pop up on the right side of the page?

**Comment by bryceosterhaus** [comment]
@john-co no, we just want to make sure the dropdowns aren't rendering on the side of the page, like this image, https://user-images.githubusercontent.com/28923749/75676671-7eaf6700-5c68-11ea-950f-5917ffc25256.png.

Can you also click around a bit and test other dropdowns in rtl? Overall we just want to make sure its not aligning on the right edge of the window, and making sure its aligning near the button itself.

**Comment by john-co** [comment]
Hi @bryceosterhaus, I didn't notice anything else odd on the dropdown menus while exploratory testing portal in rtl.

**Comment by bryceosterhaus** [comment]
Great! Thanks for checking, Ill send to bchan

**Pull request closed without merging**
