### PR TITLE
LRQA-55541 | master

### PR DESCRIPTION
**Pull request by john-co**
https://issues.liferay.com/browse/LRQA-55541

### CODE REVIEW

**Comment by john-co** [comment]
ci:test:sf

**Comment by john-co** [comment]
ci:test:poshi

**Comment by john-co** [comment]
Hi @JoyceWang08211 , it seems like StagingActivation#CheckPublicationSummaryRemote is flaky based on history https://testray.liferay.com/home/-/testray/case_results/1238442296/history?tab=result&hideFilterPin=true

**Comment by john-co** [comment]
ci:forward

**Comment by JoyceWang08211** [comment]
> Hi @JoyceWang08211 , it seems like StagingActivation#CheckPublicationSummaryRemote is flaky based on history https://testray.liferay.com/home/-/testray/case_results/1238442296/history?tab=result&hideFilterPin=true

This flaky failure is caused by page crash which is reported in [LRCI-1048](https://issues.liferay.com/browse/LRCI-1048).

**Pull request closed without merging**
