### PR TITLE
LPS-118767, LPS-118769 | master

### PR DESCRIPTION
**Pull request by zhangyan0701**
https://issues.liferay.com/browse/LPS-118767
https://issues.liferay.com/browse/LPS-118769

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by john-co** [comment]
Looks good, can you also test out removing the non-semantics elements from the other locators?

```
<tr>
	<td>HEADER</td>
	<td>//div[contains(@class,'modal-dialog')]//div[contains(@*,'modal-title')]</td>
	<td></td>
</tr>
<tr>
	<td>CLOSE_BUTTON</td>
	<td>//div[h3[@class='modal-title']]//button[contains(@class,'close')]</td>
	<td></td>
</tr>
<tr>
	<td>BODY</td>
	<td>//div[contains(@class,'modal-dialog')]//*[contains(@class,'modal-body')]</td>
	<td></td>
</tr>
```
I think the CLOSE_BUTTON can be replaced with Button#ANY as well.

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
CLOSE_BUTTON cannot be replaced with Button#ANY because it doesn't contains text, but it can be replace by Icon#CLOSE.

**Comment by john-co** [comment]
Looks good, I made the Button#CLOSE_MODAL more generic and simple.
https://github.com/john-co/liferay-portal/pull/323/commits/3cc144f7fc427f895885e9e74b1a54d455b4c951

I think the macros could use some refactoring later...it doesn't seem clean to have the key_modalTitle initialized outside the click...if we can't initialize it within the Click function then probably better with macro Modal.Close. Will want to build out macro file for Modal.macro and consolidate IFrame.macro in another task.

**Comment by john-co** [comment]
ci:forward

**Pull request closed without merging**
