### PR TITLE
master-qa-120833

### PR DESCRIPTION
**Pull request by zhangyan0701**
https://issues.liferay.com/browse/LPS-120833

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by john-co** [comment]
looks good! same comment as the other PR about `&amp`, not a deal breaker since overwhelming majority of tests have this formatting so will forward. :+1:

**Comment by john-co** [comment]
ci:forward

**Pull request closed without merging**
