### PR TITLE
master-qa-61828

### PR DESCRIPTION
**Pull request by zhangyan0701**
https://issues.liferay.com/browse/LRQA-61828

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by john-co** [comment]
ci:test:relevant

**Comment by john-co** [comment]
looks like the tests were impacted by the load balancer outage: https://liferay.slack.com/archives/C19PWQ74J/p1600784622026100

**Review by john-co — APPROVED** [review]
Looks good!

**Comment by john-co** [comment]
ci:forward

**Pull request closed without merging**
