### PR TITLE
LPS-91967  Yarn

### PR DESCRIPTION
**Pull request by petershin**

### CODE REVIEW

**Comment by petershin** [comment]
ci:test

**Comment by petershin** [comment]
@john-co - Added fixes for a few tests: https://github.com/john-co/liferay-portal/pull/92/commits/38c536d751abc68a6012f925ecb8c7476a57c380

**Comment by john-co** [comment]
@jbalsas There seems to be some compile issues for some frontend apps. Functional test wise there are some tests affected I can write up test fixes for those on Monday.

**Comment by jbalsas** [comment]
Doesn't make sense that functional tests are affected here, since we don't change any code... 🤔

**Comment by petershin** [comment]
Sent rebased pull to Chema: https://github.com/jbalsas/liferay-portal/pull/1694

**Comment by petershin** [comment]
Latest pull: https://github.com/jbalsas/liferay-portal/pull/1703

**Pull request closed without merging**
