### PR TITLE
master-qa-51442

### PR DESCRIPTION
**Pull request by zhangyan0701**
https://issues.liferay.com/browse/LRQA-51442

This issue also affects 7.2.x, please backport to 7.2.x, thanks!

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by john-co** [comment]
Just started reviewing :)

**Comment by john-co** [comment]
LGTM, thanks!
Pushed to BChan
master: https://github.com/brianchandotcom/liferay-portal/pull/77099
7.2.x: https://github.com/brianchandotcom/liferay-portal-ee/pull/26021

**Pull request closed without merging**
