### PR TITLE
LPS-104395 - Remove elementClasses in favor of style prop

### PR DESCRIPTION
**Pull request by bryceosterhaus**
Note, that these classes weren't needed in the first place since the "style" prop is taking priority. `btn-default` wasn't actually applying any styles since `btn-primary` and `btn-link` were priority since they were declared via the style prop(`btn-primary` is the default value).

### CODE REVIEW

**Comment by bryceosterhaus** [comment]
ci:test

**Comment by john-co** [comment]
ci:test:stable

**Comment by john-co** [comment]
possible fluke:
RecycleBin#RestoreDMDocumentFromFolderCP

**Comment by john-co** [comment]
ci:test:bundle

**Comment by john-co** [comment]
Pushed to BChan:
master: https://github.com/brianchandotcom/liferay-portal/pull/80774

**Comment by john-co** [comment]
Test results currently look good enough.

**Pull request closed without merging**
