### PR TITLE
master-qa-54668

### PR DESCRIPTION
**Pull request by zhangyan0701**
https://issues.liferay.com/browse/LRQA-54668
https://issues.liferay.com/browse/LRQA-54671

Issues also affect 7.2.x, please backport to 7.2.x. Thanks!

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by john-co** [comment]
Pushed to BChan:
master: https://github.com/brianchandotcom/liferay-portal/pull/82692
7.2.x: https://github.com/brianchandotcom/liferay-portal-ee/pull/28309

**Comment by john-co** [comment]
looks good to me!

**Pull request closed without merging**
