### PR TITLE
LPS 139932 - [Test Fix] Move list title to an upper level

### PR DESCRIPTION
**Pull request by john-co**
- LPS-139932 Change list to dl (Description List element) in order to respect this accessibility criteria 1.3.1 Info and Relationships, 2.4.6 Headings and Labels
- LPS-139932 Update paths affected by ul li change to dl dd element tags

### CODE REVIEW

**Comment by john-co** [comment]
ci:test:sf

**Comment by john-co** [comment]
ci:test:relevant

**Comment by john-co** [comment]
ci:test:acceptance-functional

**Comment by john-co** [comment]
ci:test:relevant

**Comment by john-co** [comment]
ci:test:relevant

**Comment by john-co** [comment]
ci:test:relevant:norebase

**Comment by john-co** [comment]
ci:test:upstream-functional:norebase

**Comment by john-co** [comment]
[Related]
- Managment Toolbar Contextualized Toolbar does not appear

https://user-images.githubusercontent.com/35235266/142274804-a9c3fa03-3d44-490d-9b18-7497d40c4449.mp4

**Comment by georgel-pop-lr** [comment]
> [Related]
> 
> * Managment Toolbar Contextualized Toolbar does not appear
> 
>  ManagementToolBar_ContextualToolsDoesNotAppear.mp4

Hi @john-co,

I could reproduce this regression, I'm checking it out.

Thanks and regards.

**Comment by john-co** [comment]
ci:test:upstream-functional

**Comment by john-co** [comment]
There are too many new tests failing recently to do a proper comparison...Running a baseline upstream run in https://github.com/john-co/liferay-portal/pull/445

**Comment by john-co** [comment]
@zhangyan0701 would you be able to analyze the remaining test failures on https://github.com/john-co/liferay-portal/pull/442#issuecomment-983358400? Hopefully a more similar baseline upstream run is available by your time zone.

**Comment by zhangyan0701** [comment]
Just start reviewing

**Comment by zhangyan0701** [comment]
I checked the test results, there are some related failures:

1. In Content Dashboard, no results displays if filter content by author displaying as list:
content dashboard

2. Object cannot be selected in content page edit mode when configuring mapping for fragment:

Steps:
- Go to Control Panel > Objects, create a new object, Label: Custom Object, under Panel Category Key, select Control Panel > Object. 
- Go into the object, navigate to Fields tab, create one Boolean type field.
- Go to Control Panel > Custom Object, create a new entry, check the Boolean field.
- Add a new content page, in edit mode, add a heading fragment into the page.
- Click the heading fragment, then click element-text in the side panel.
- In Mapping, click Select Item and select the created custom object.
- Assert the custom object doesn't display under Mapping.

objects1

**Comment by zhangyan0701** [comment]
There are also some test fix, more li and ul paths needs to be updated, I send here:
https://github.com/zhangyan0701/liferay-portal/pull/319

**Comment by john-co** [comment]
Thanks @zhangyan0701 , I'll fetch and push to @georgel-pop-lr 's branch

**Comment by georgel-pop-lr** [comment]
> I checked the test results, there are some related failures:
> 
> **1. In Content Dashboard, no results displays if filter content by author displaying as list:**
> 
> content dashboard
> 
> **2. Object cannot be selected in content page edit mode when configuring mapping for fragment:**
> 
> Steps:
> 
> * Go to Control Panel > Objects, create a new object, Label: Custom Object, under Panel Category Key, select Control Panel > Object.
> * Go into the object, navigate to Fields tab, create one Boolean type field.
> * Go to Control Panel > Custom Object, create a new entry, check the Boolean field.
> * Add a new content page, in edit mode, add a heading fragment into the page.
> * Click the heading fragment, then click element-text in the side panel.
> * In Mapping, click Select Item and select the created custom object.
> * Assert the custom object doesn't display under Mapping.
> 
> objects1

I will need to check out this case. 

Regards.

**Pull request closed without merging**
