### PR TITLE
pr-162 | master

### PR DESCRIPTION
**Pull request by john-co**
https://issues.liferay.com/browse/pr-162

### CODE REVIEW

**Comment by john-co** [comment]
ci:test:sf

**Comment by john-co** [comment]
ci:test

**Comment by john-co** [comment]
ci:test

**Comment by wincent** [comment]
I have no idea how our CI stuff runs 🤦‍♂️ but please let me know if we need to make further changes in liferay-npm-tools to make all this work.

**Comment by john-co** [comment]
ci:test

**Comment by john-co** [comment]
Hi @wincent, I'll let you know. It looks like the changes didn't affect CI output the way I hoped it would. But we discovered there was a logic bug in the ant scripts that may be the cause of what we're trying to fix. I'm investigating further, unfortunately the last ci test run came up with an unexpected error...

**Comment by john-co** [comment]
ci:test:norebase

**Pull request closed without merging**
