### PR TITLE
LRQA-44612 - Regen package-lock files

### PR DESCRIPTION
**Pull request by bryceosterhaus**

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test

**Comment by bryceosterhaus** [comment]
@john-co I am getting a failed `npmRunTest` for "dynamic-data-mapping-form-builder" on my local master as well. Are you seeing this at all?

**Comment by john-co** [comment]
@bryceosterhaus, 
Yes I'm seeing a failure at head as well...this is what I'm getting:
https://gist.github.com/john-co/7615118b5b7bc0548d958ad402739f5f

**Comment by john-co** [comment]
created ticket to track the blocking issue https://issues.liferay.com/browse/LPS-89930

**Pull request closed without merging**
