### PR TITLE
master-qa-61858

### PR DESCRIPTION
**Pull request by zhangyan0701**
https://issues.liferay.com/browse/LRQA-61858

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by john-co** [comment]
Looks good!

**Comment by john-co** [comment]
ci:forward

**Comment by zhangyan0701** [comment]
ci:forward

**Comment by john-co** [comment]
ci:forward

**Review by john-co — APPROVED** [review]

**Pull request closed without merging**
