### PR TITLE
LRQA-61008 | master

### PR DESCRIPTION
**Pull request by zhangyan0701**
https://issues.liferay.com/browse/LRQA-61008

Test passed in https://github.com/zhangyan0701/liferay-portal/pull/232.

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by john-co** [comment]
Looks good!

**Comment by john-co** [comment]
ci:forward

**Pull request closed without merging**
