### PR TITLE
LPS-106862 Update liferay-npm-scripts to 17.0.4

### PR DESCRIPTION
**Pull request by izaera**
Let's see if this fixes it :crossed_fingers: 

I can confirm that `ant all` goes well in Linux and Windows.

### CODE REVIEW

**Comment by izaera** [comment]
ci:test

**Comment by john-co** [comment]
ci:test:relevant

**Comment by john-co** [comment]
ci:test:sf

**Comment by john-co** [comment]
**Reviewed. Test failures are unrelated.** :heavy_check_mark: 
- js-unit tests pass in `relevant test` run.

**Comparison details for `ci test`:**
https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=950839622&testrayRunIdA=952210346&statusB=2

- verified as flukes and flaky tests

**Comment by john-co** [comment]
Pushed to BChan.
master: https://github.com/brianchandotcom/liferay-portal/pull/83235

**Pull request closed without merging**
