### PR TITLE
master-qa-118763

### PR DESCRIPTION
**Pull request by zhangyan0701**
https://issues.liferay.com/browse/LPS-118763

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by john-co** [comment]
looks good to me!

Upon further review, I think the dropdown.path can be further investigated/refactored. Other paths have non-semantic elements that could be replaced with //*. Also some locators don't have any reference to dropdown class or similar to identify that it's a dropdown item...

Maybe even better option, could these paths be consolidated in MenuItem#DROPDOWN_MENU_ITEM?

**Comment by john-co** [comment]
ci:forward

**Pull request closed without merging**
