### PR TITLE
master-qa-54806

### PR DESCRIPTION
**Pull request by zhangyan0701**
https://issues.liferay.com/browse/LRQA-54806

This is for master only.

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by john-co** [comment]
looks good to me!

**Comment by john-co** [comment]
Pull request forwarded to https://github.com/brianchandotcom/liferay-portal/pull/82758. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
