### PR TITLE
master-qa-45941

### PR DESCRIPTION
**Pull request by zhangyan0701**
https://issues.liferay.com/browse/LRQA-45941

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by john-co** [comment]
Just started reviewing :)

**Comment by john-co** [comment]
iirc there's no current infrastructure to test on IE11 in pr tester. Testing locally on IE11 also lags. Since almost all tests are currently failing, let's push this up and monitor environment acceptance 7.2.x-private: https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=479969175

**Comment by john-co** [comment]
Pushed to BChan:
master: https://github.com/brianchandotcom/liferay-portal/pull/76462
7.2.x: https://github.com/brianchandotcom/liferay-portal-ee/pull/25753

**Pull request closed without merging**
