### PR TITLE
LPS12345

### PR DESCRIPTION
**Pull request by eltonccdantas**

### CODE REVIEW

**Comment by eltonccdantas** [comment]
[Log](https://gist.github.com/eltonccdantas/53afa4019e5e659a2c1d4abf917294e4) when I ran the test locally

**Comment by eltonccdantas** [comment]
ci:test:relevant:nocompile

**Comment by eltonccdantas** [comment]
ci:help

**Comment by eltonccdantas** [comment]
ci:stop

**Comment by eltonccdantas** [comment]
ci:stop:relevant

**Comment by mateusralv** [comment]
ci:test:relevant

**Comment by mateusralv** [comment]
ci:test:sf

**Comment by mateusralv** [comment]
ci:test:relevant

**Comment by eltonccdantas** [comment]
ci:test:sf

**Comment by eltonccdantas** [comment]
ci:test:relevant

**Comment by eltonccdantas** [comment]
[Poshi Report](https://drive.google.com/file/d/1hiXKVHaLq2X3i-FK5QuqYOuUI9ZOKdm6/view?usp=sharing) when I ran it locally.

**Comment by john-co** [comment]
ci:test:nocompile

**Comment by john-co** [comment]
ci:test

**Comment by eltonccdantas** [comment]
ci:help

**Comment by eltonccdantas** [comment]
ci:stop:relevant

**Comment by eltonccdantas** [comment]
ci:stop

**Comment by eltonccdantas** [comment]
ci:test:relevant:nocompile

**Comment by eltonccdantas** [comment]
ci:test:relevant

**Comment by john-co** [comment]
ci:test:nocompile

**Comment by john-co** [comment]
ci:test

**Comment by eltonccdantas** [comment]
ci:test

**Pull request closed without merging**
