### PR TITLE
LPS-92354

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @john-co,

Attached is an update for http://issues.liferay.com/browse/LPS-92354.

I sent this to you to review since last time i created a regression.  I wanted to make sure it was good before merging into master.

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by john-co** [comment]
ci:test:relevant

**Comment by john-co** [comment]
@jonmak08, looks good to me!

**Comment by jonmak08** [comment]
New Pull Request: https://github.com/brianchandotcom/liferay-portal/pull/71946

**Pull request closed without merging**
