### PR TITLE
master-qa-52712

### PR DESCRIPTION
**Pull request by zhangyan0701**
https://issues.liferay.com/browse/LRQA-52712
https://issues.liferay.com/browse/LRQA-52714
https://issues.liferay.com/browse/LRQA-52721

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by john-co** [comment]
Just started reviewing :)

**Comment by john-co** [comment]
looks good, thanks @zhangyan0701!

**Comment by john-co** [comment]
Pushed to BChan:
master: https://github.com/brianchandotcom/liferay-portal/pull/79775
7.2.x: https://github.com/brianchandotcom/liferay-portal-ee/pull/27148

**Pull request closed without merging**
