### PR TITLE
LRCI-1041 | master

### PR DESCRIPTION
**Pull request by john-co**
https://issues.liferay.com/browse/LRCI-1041

### CODE REVIEW

**Comment by john-co** [comment]
ci:test:sf

**Comment by john-co** [comment]
ci:test:relevant

**Comment by john-co** [comment]
ci:test:relevant

**Comment by john-co** [comment]
ci:test:sf

**Comment by john-co** [comment]
ci:test:poshi

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
ci:test:poshi

**Comment by john-co** [comment]
Feedback on the test runs I ran yesterday:

@zhangyan0701 findings:
There were two tests failed to run because the chrome binary couldn't be found:
```
org.openqa.selenium.WebDriverException: unknown error: no chrome binary at /opt/google/chrome-stable-86/google-chrome
```
Jenkins log:
[CPRolesCPWebcontent#AddFolderSiteRoleDefinePermission](https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=5,label_exp=!master/427301/testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_CPRolesCPWebcontent_AddFolderSiteRoleDefinePermission_/)
[WorkflowUpgrade#SubmitAndApproveWorkflowAfterUpgrade7110](https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=6,label_exp=!master/342089/testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_WorkflowUpgrade_SubmitAndApproveWorkflowAfterUpgrade7110_/)

@kenjiheigel replied:
that may happen from time to time… because some of the Jenkins nodes coming back online don’t have chrome installed. i’m running something that will catch those nodes in verification, but there are cases like this one, where it may slip through

**Comment by john-co** [comment]
ci:test:relevant

**Comment by john-co** [comment]
Discussed with Kenji, and we think that applying the retry rule will help fix the instability with the missing chrome 86 binary.

**Comment by pyoo47** [comment]
ci:forward

**Pull request closed without merging**
