### PR TITLE
LRQA-62024 | master

### PR DESCRIPTION
**Pull request by PablitoBonito**
https://issues.liferay.com/browse/LRQA-62024

### CODE REVIEW

**Comment by PablitoBonito** [comment]
ci:test:sf

**Comment by PablitoBonito** [comment]
ci:test:relevant

**Comment by john-co** [comment]
@PablitoBonito, there's 42 files that are in this commit. We only want to send relevant files...I think you probably added files modified by source formatter. Are you still seeing a bunch of files being modified when running `ant format-source-all`?

**Comment by john-co** [comment]
We need to fix this first so I can perform a proper review of the relevant files.

**Pull request closed without merging**
