### PR TITLE
master-qa-52720

### PR DESCRIPTION
**Pull request by zhangyan0701**
https://issues.liferay.com/browse/LRQA-52720

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by john-co** [comment]
Just started reviewing :)

**Comment by john-co** [comment]
Pushed to BChan:
master: https://github.com/brianchandotcom/liferay-portal-ee/pull/27477
7.2.x: https://github.com/brianchandotcom/liferay-portal-ee/pull/27477

**Comment by john-co** [comment]
Looks good!

**Pull request closed without merging**
