### PR TITLE
LRQA-76201 | master

### PR DESCRIPTION
**Pull request by Kvale1733**
https://issues.liferay.com/browse/LRQA-76201

### CODE REVIEW

**Comment by Kvale1733** [comment]
@john-co These test changes fix two Core tests that are broken by Chrome 100.

**Comment by Kvale1733** [comment]
ci:test:sf

**Comment by john-co** [comment]
ci:help

**Comment by john-co** [comment]
Hi Kvale1733,
Please attach poshi reports to the ticket to show that they now pass with the commits.

Also, please fetch and rebase with the commits from https://github.com/john-co/liferay-portal/pull/463/commits
Because a widely used DDL macro was touched please run `ci:test:forms` and check there are no new regressions.

**Comment by Kvale1733** [comment]
ci:close

**Comment by Kvale1733** [comment]
ci:reopen

**Comment by Kvale1733** [comment]
@john-co https://github.com/john-co/liferay-portal/pull/463 now has merge conflicts btw.

**Comment by john-co** [comment]
thanks! rebased

**Comment by Kvale1733** [comment]
ci:test:forms

**Comment by Kvale1733** [comment]
Tested the two affected tests here and they are passing on CI: https://github.com/Kvale1733/liferay-portal/pull/147

**Comment by Kvale1733** [comment]
@john-co The tests pass on CI as shown here: https://github.com/Kvale1733/liferay-portal/pull/147 and the Forms test suite does not show any failures caused by the change in the DDL macro.

**Comment by john-co** [comment]
Thanks @Kvale1733 ! I'll add the commits in.

**Review by john-co — APPROVED** [review]
Looks good to me! :sunglasses:

**Comment by john-co** [comment]
Added to https://github.com/john-co/liferay-portal/pull/463

**Pull request closed without merging**
