### PR TITLE
LRQA-56415 | Master

### PR DESCRIPTION
**Pull request by nkkwon**
https://issues.liferay.com/browse/LRQA-56415
https://issues.liferay.com/browse/LRQA-56409

### CODE REVIEW

**Comment by nkkwon** [comment]
I think you may need to pull master

**Comment by john-co** [comment]
does the test pass on ci?

**Comment by john-co** [comment]
@nkkwon, can you make sure the test passes on ci?

You can run a single test with something like this: https://github.com/john-co/liferay-portal/pull/244/commits/10bdb689dd6abb2c210262152e587df7ce68e704

**Comment by nkkwon** [comment]
@john-co Yup it passes on CI, check https://github.com/nkkwon/liferay-portal/pull/4

**Comment by john-co** [comment]
awesome, thanks. I see you already made the changes. Are we able to avoid using the pause? I think we can possibly waitFor a css for full opacity.

**Comment by john-co** [comment]
Selection_145
maybe something that waits for opacity: 1

**Comment by john-co** [comment]
Just started reviewing :)

**Comment by john-co** [comment]
The ci tests in https://github.com/nkkwon/liferay-portal/pull/10 don't include UIInfrastructureUsecase#ViewPortletBoundries

Running test here: https://github.com/john-co/liferay-portal/pull/294

**Comment by john-co** [comment]
please see adjustments in https://github.com/john-co/liferay-portal/pull/295

**Pull request closed without merging**
