### PR TITLE
LRQA-56230

### PR DESCRIPTION
**Pull request by Adriverforlife**

### CODE REVIEW

**Comment by john-co** [comment]
ci:test:sf

**Comment by john-co** [comment]
ci:test

**Comment by john-co** [comment]
ci:test:relevant

**Comment by Adriverforlife** [comment]
https://github.com/Adriverforlife/liferay-portal/pull/6

**Comment by john-co** [comment]
ci:forward

**Comment by john-co** [comment]
looks good! test passes in https://github.com/Adriverforlife/liferay-portal/pull/6

**Comment by john-co** [comment]
ci:stop

**Pull request closed without merging**
