### PR TITLE
master-qa-59610

### PR DESCRIPTION
**Pull request by zhangyan0701**
https://issues.liferay.com/browse/LRQA-59610
https://issues.liferay.com/browse/LRQA-59038

### CODE REVIEW

**Comment by zhangyan0701** [comment]
Added property testray.component.names = "WYSIWYG" into test UIInfrastructureUsecase#RightToLeftSmoke, because this is the only test that navigate to Web Content edit page (which contains alloy editor and ckeditor) though URL that with locale. I think it's better that run this test when we update module frontend-editor.

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
ci:test:revelant

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by john-co** [comment]
Just started reviewing :)

**Comment by john-co** [comment]
lgtm!

**Comment by john-co** [comment]
ci:forward

**Pull request closed without merging**
