### PR TITLE
LPS-110927 | master

### PR DESCRIPTION
**Pull request by john-co**
https://issues.liferay.com/browse/LPS-110927

### CODE REVIEW

**Comment by john-co** [comment]
ci:test:sf

**Comment by john-co** [comment]
ci:test:relevant

**Comment by john-co** [comment]
ci:stop

**Comment by john-co** [comment]
ci:stop

**Comment by john-co** [comment]
ci:test:sf

**Comment by john-co** [comment]
ci:test:relevant

**Comment by john-co** [comment]
ci:stop

**Comment by john-co** [comment]
ci:test:poshi

**Comment by wincent** [comment]
Latest: https://github.com/john-co/liferay-portal/pull/291

**Comment by john-co** [comment]
Reviewing test failures.

This branch includes the latest auto SF from #291

**Comment by john-co** [comment]
[Not Related] Failing in upstream
- AppBuilder#PredefinedValuesArePersistedInFormView
- AppBuilder#SetAppBuilderManagePermissionFor2RolesAndPerformCRUD
- WebContentDisplay#AddAudioViaWebContent

Will need further investigation, not sure if related to iframe
- ViewSLABreachesOfTopSteps

**Comment by john-co** [comment]
Temp ignore tests, pending poshi iframe macro:
- CalendarManagCalendar#SearchForOtherCalendars
- OpenGraphImages#ViewImageWithMetaTags
- StagingDMWithvariation#StagingDemoDocumentsAndMedia
- StagingActivation#CheckPublicationSummaryRemote
- StagingUsecase#TrashEntryReferencePublishing

**Comment by john-co** [comment]
ci:test:relevant

**Comment by john-co** [comment]
ci:test:poshi

**Comment by john-co** [comment]
WorkflowMetrics#ViewSLABreachesOfTopSteps is possibly flaky, not able to reproduce issue locally.

**Comment by john-co** [comment]
ci:test:sf

**Comment by john-co** [comment]
sf errors look unrelated, most likely caused by https://github.com/liferay/liferay-portal/commit/77b112fc5ce2d3d04ea1f1952073bc0f1495a251

**Comment by john-co** [comment]
@markocikos looks like the js unit snapshot failures are related.

```
> Task :apps:frontend-js:frontend-js-web:packageRunTest
yarn run v1.13.0
warning package.json: No license field
$ liferay-npm-scripts test
Compiling soy
Generated build/npmscripts/soy/liferay/compat/modal/Modal.soy.js
Finished compiling soy
Successfully compiled 1 file with Babel.
Using NODE_ENV: "test"
PASS test/liferay/CompatibilityEventProxy.es.js
PASS test/liferay/component.es.js
PASS test/liferay/PortletBase.es.js
PASS test/liferay/aop/AOP.es.js
PASS test/liferay/portlet/in_progress.es.js
PASS test/liferay/util/portlet_url/create_portlet_url.es.js
PASS test/liferay/portlet/state.es.js
PASS test/liferay/portlet/action.es.js
PASS test/liferay/util/fetch.es.js
PASS test/liferay/portlet/create_resource_url.es.js
PASS test/liferay/util/form/object_to_form_data.es.js
PASS test/liferay/util/add_params.js
PASS test/liferay/portal/tabs.es.js
PASS test/liferay/util/navigate.es.js
PASS test/liferay/util/form/post_form.es.js
PASS test/liferay/util/get_crop_region.es.js
PASS test/liferay/throttle.es.js
PASS test/liferay/util/format_xml.es.js
PASS test/liferay/util/session.es.js
PASS test/liferay/util/form/get_form_element.es.js
PASS test/liferay/debounce/debounce.es.js
PASS test/liferay/util/format_storage.es.js
PASS test/liferay/portlet/events.es.js
PASS test/liferay/util/toggle_disabled.js
PASS test/liferay/util/object_to_url_search_params.es.js
PASS test/liferay/util/form/set_form_values.es.js
PASS test/liferay/util/normalize_friendly_url.js
PASS test/liferay/util/portlet_url/create_action_url.es.js
PASS test/liferay/util/portlet_url/create_resource_url.es.js
PASS test/liferay/util/ns.es.js
PASS test/liferay/util/portlet_url/create_render_url.es.js
PASS test/liferay/portlet/register.es.js
PASS test/liferay/util/get_portlet_id.js
PASS test/liferay/util/get_portlet_namespace.es.js
PASS test/liferay/util/address/get_countries.es.js
PASS test/liferay/util/address/get_regions.es.js
PASS test/liferay/util/to_char_code.es.js
FAIL test/liferay/modal/Modal.js
  ● Modal › renders markup based on given configuration

    expect(received).toMatchSnapshot()

    Snapshot name: `Modal renders markup based on given configuration 1`

    - Snapshot  - 2
    + Received  + 2

    @@ -51,12 +51,12 @@
                      aria-hidden="true"
                      class="loading-animation"
                    />
                    <iframe
                      class="hide"
    -                 src="https://www.sample.url/?p_p_id=com_liferay_MyPortlet&_com_liferay_MyPortlet_bodyCssClass=dialog-iframe-popup"
    -                 title="https://www.sample.url/?p_p_id=com_liferay_MyPortlet&_com_liferay_MyPortlet_bodyCssClass=dialog-iframe-popup"
    +                 src="https://www.sample.url/?p_p_id=com_liferay_MyPortlet"
    +                 title="https://www.sample.url/?p_p_id=com_liferay_MyPortlet"
                    />
                  </div>
                </div>
              </div>
            </div>

      38 | 		});
      39 | 
    > 40 | 		expect(baseElement).toMatchSnapshot();
         | 		                    ^
      41 | 	});
      42 | 
      43 | 	it('renders in full screen, if url is set', () => {

      at Object.toMatchSnapshot (test/liferay/modal/Modal.js:40:23)

 › 1 snapshot failed.
Summary of all failing tests
FAIL test/liferay/modal/Modal.js
  ● Modal › renders markup based on given configuration

    expect(received).toMatchSnapshot()

    Snapshot name: `Modal renders markup based on given configuration 1`

    - Snapshot  - 2
    + Received  + 2

    @@ -51,12 +51,12 @@
                      aria-hidden="true"
                      class="loading-animation"
                    />
                    <iframe
                      class="hide"
    -                 src="https://www.sample.url/?p_p_id=com_liferay_MyPortlet&_com_liferay_MyPortlet_bodyCssClass=dialog-iframe-popup"
    -                 title="https://www.sample.url/?p_p_id=com_liferay_MyPortlet&_com_liferay_MyPortlet_bodyCssClass=dialog-iframe-popup"
    +                 src="https://www.sample.url/?p_p_id=com_liferay_MyPortlet"
    +                 title="https://www.sample.url/?p_p_id=com_liferay_MyPortlet"
                    />
                  </div>
                </div>
              </div>
            </div>

      38 | 		});
      39 | 
    > 40 | 		expect(baseElement).toMatchSnapshot();
         | 		                    ^
      41 | 	});
      42 | 
      43 | 	it('renders in full screen, if url is set', () => {

      at Object.toMatchSnapshot (test/liferay/modal/Modal.js:40:23)


Snapshot Summary
 › 1 snapshot failed from 1 test suite. Inspect your code changes or re-run jest with `-u` to update them.

Test Suites: 1 failed, 37 passed, 38 total
Tests:       1 failed, 1 skipped, 315 passed, 317 total
Snapshots:   1 failed, 5 passed, 6 total
Time:        4.725s
```

**Comment by john-co** [comment]
ci:close

**Comment by markocikos** [comment]
> @markocikos looks like the js unit snapshot failures are related. I updated the snapshot in #293 please let me know if ok.

@john-co Yep, that's a good update :+1:

**Pull request closed without merging**
