### PR TITLE
LRQA-44612 - Use liferay-npm-scripts@v1.1.0 for updated test reporter

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test

**Comment by john-co** [comment]
> Looks like we had some flaky `npmInstall` runs... also, @john-co, is this the expected output? Looks pretty similar to me than before... what there is the expected output from the new format? I think this might not apply to some modules with tests, so we'll need to apply the new scripts there as well to have a more clear idea.
> 
> test-results

@jbalsas This is not the expected output. Seems like nothing has changed...We should have something similar to what was shared in liferay-npm-tools.

**Comment by jbalsas** [comment]
ci:test

**Comment by jbalsas** [comment]
Closing in favour of https://github.com/john-co/liferay-portal/pull/53

**Pull request closed without merging**
