### PR TITLE
LPS-XXX - Update dependencies

### PR DESCRIPTION
**Pull request by bryceosterhaus**

### CODE REVIEW

**Comment by bryceosterhaus** [comment]
ci:test

**Comment by bryceosterhaus** [comment]
@john-co any idea why this is failing?

**Comment by john-co** [comment]
Hi @bryceosterhaus looks like a rebase issue on modules/dxp/apps/analytics/analytics-reports-web/package.json

https://github.com/john-co/liferay-portal/pull/256/conflicts

**Comment by john-co** [comment]
Pull request submitted to https://github.com/john-co/liferay-portal/pull/257. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
