### PR TITLE
LPS-83829 SF

### PR DESCRIPTION
**Pull request by julien**

### CODE REVIEW

**Comment by julien** [comment]
ci:test

**Comment by julien** [comment]
Hi @john-co,

Please see https://github.com/jpince/liferay-portal/pull/89#issuecomment-436684240

Note: I'm not really sure why the source format output is not the same on CI as when running it locally.

**Comment by john-co** [comment]
@jpince, can you check the failing integration test? It looks like a fluke but want to double check with you.

I am not able to reproduce LPS-86920 with the bundle.

**Comment by jpince** [comment]
@john-co you're correct. It's an flaky database connection issue.
`     [exec] ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/opt/mariadb/data/mariadb.sock' (2)`

Please forward to BChan if your testing/analysis is complete.

**Comment by john-co** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/64865

**Pull request closed without merging**
